#!/usr/bin/env ruby

def download_from_youtube(yt_id, sample_filename)
  system("youtube-dl -f mp4 https://www.youtube.com/watch?v=#{yt_id} -o '#{sample_filename}.%(ext)s'")
end

def convert_to_wav(sample_filename)
  system("ffmpeg -i #{sample_filename}.mp4 #{sample_filename}.wav")
  system("rm #{sample_filename}.mp4")
end

def store_to_disk(sample_filename)
  system("mv #{sample_filename}.wav #{ENV["SAMPLES_STORAGE_PATH"]}")
end




def main()
  download_from_youtube(ARGV[0], ARGV[1])
  convert_to_wav(ARGV[1])
  store_to_disk(ARGV[1])
end

main